from pptx import Presentation
import os
import re

def create_ppt(topic, repos):
    # Clean topic for safe filename
    safe_topic = re.sub(r'[\\/*?:"<>|\n\r]+', "_", topic.strip())
    if len(safe_topic) > 60:
        safe_topic = safe_topic[:60]

    prs = Presentation()

    # Slide 1: Title
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = f"Hackathon Project: {topic.splitlines()[0]}"
    slide.placeholders[1].text = "Generated by Hackathon Idea Generator"

    # Slide 2: Overview
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Overview"
    slide.placeholders[1].text = (
        f"This project '{topic.splitlines()[0]}' aims to address real-world hackathon challenges "
        "by integrating AI-driven insights and open-source resources."
    )

    # Slide 3: Repositories
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Related Repositories"
    if repos:
        content = "\n".join([f"- {r['name']}: {r['html_url']}" for r in repos[:5]])
    else:
        content = "No related repositories found."
    slide.placeholders[1].text = content

    # Save PPT
    os.makedirs("generated_ppts", exist_ok=True)
    ppt_path = os.path.join("generated_ppts", f"{safe_topic}.pptx")
    prs.save(ppt_path)
    return ppt_path
